name: little_library
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  page_transition: ^2.0.9
  google_maps_flutter: ^2.4.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.5.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  geocoding: ^2.1.1
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    # fonts:
    #   - family: Roboto
    #     fonts:
    #       - asset: fonts/Roboto-Regular.ttf
    #       - asset: fonts/Roboto-Bold.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
